'use strict';

const crypto = require('crypto');
const axios = require('axios');
const jwt = require('jsonwebtoken');
const config = require('../config');
const threadsService = require('../services/threadsService');

const META_AUTH_URL = 'https://threads.net/oauth/authorize';
const META_TOKEN_URL = 'https://graph.threads.net/oauth/access_token';
const META_LONG_LIVED_URL = 'https://graph.threads.net/access_token';

/**
 * Generate a CSRF state token: random bytes signed with HMAC-SHA256.
 * Verification does not require server-side storage.
 * @returns {string}
 */
function generateState() {
  const random = crypto.randomBytes(16).toString('hex');
  const hmac = crypto
    .createHmac('sha256', config.jwtSecret)
    .update(random)
    .digest('hex');
  return `${random}.${hmac}`;
}

/**
 * Verify a state token generated by generateState().
 * Uses timing-safe comparison to prevent timing attacks.
 * @param {string} state
 * @returns {boolean}
 */
function verifyState(state) {
  try {
    if (!state || typeof state !== 'string') return false;
    const dotIdx = state.indexOf('.');
    if (dotIdx < 0) return false;
    const random = state.slice(0, dotIdx);
    const signature = state.slice(dotIdx + 1);
    const expected = crypto
      .createHmac('sha256', config.jwtSecret)
      .update(random)
      .digest('hex');
    const sigBuf = Buffer.from(signature, 'hex');
    const expBuf = Buffer.from(expected, 'hex');
    if (sigBuf.length !== expBuf.length) return false;
    return crypto.timingSafeEqual(sigBuf, expBuf);
  } catch {
    return false;
  }
}

/**
 * Build an HTML page that sends a postMessage to the opener window and closes itself.
 * Used for both success and error responses in the popup OAuth flow.
 * @param {object} data - Payload to send via postMessage
 * @param {string} targetOrigin - Allowed target origin
 * @returns {string} HTML string
 */
function buildPostMessageHtml(data, targetOrigin) {
  // JSON.stringify handles most special characters; additionally escape <, >, & to
  // prevent script injection if this page is ever rendered outside the popup context.
  const serialized = JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');

  return `<!DOCTYPE html>
<html>
  <head><meta charset="utf-8" /><title>Authentication</title></head>
  <body>
    <script>
      (function () {
        var data = ${serialized};
        try {
          if (window.opener && !window.opener.closed) {
            window.opener.postMessage(data, ${JSON.stringify(targetOrigin)});
          }
        } catch (e) { /* ignore postMessage errors */ }
        window.close();
      })();
    </script>
  </body>
</html>`;
}

/**
 * Redirect user to Meta Threads OAuth authorization page.
 * Includes a CSRF state parameter signed with HMAC-SHA256.
 */
async function initiateOAuth(req, res) {
  const state = generateState();

  const params = new URLSearchParams({
    client_id: config.meta.appId,
    redirect_uri: config.meta.redirectUri,
    scope: 'threads_basic,threads_content_publish,threads_manage_replies',
    response_type: 'code',
    state,
  });

  return res.redirect(`${META_AUTH_URL}?${params.toString()}`);
}

/**
 * Handle Meta OAuth callback, exchange code for tokens, upsert user.
 */
async function handleCallback(req, res) {
  const { code, state, error, error_description } = req.query;
  const targetOrigin = config.frontendUrl || 'http://localhost:3000';

  // Verify CSRF state first — applies to all callback paths including provider errors
  // (RFC 9700 §4.7: state must be validated even when the AS returns an error)
  if (!verifyState(state)) {
    return res
      .status(400)
      .send(buildPostMessageHtml({ type: 'oauth_error', error: 'Invalid state parameter' }, targetOrigin));
  }
  if (error) {
    return res
      .status(400)
      .send(buildPostMessageHtml({ type: 'oauth_error', error, error_description }, targetOrigin));
  }
  if (!code) {
    return res
      .status(400)
      .send(buildPostMessageHtml({ type: 'oauth_error', error: 'No authorization code provided' }, targetOrigin));
  }

  try {
    // Exchange code for short-lived token
    const tokenResponse = await axios.post(META_TOKEN_URL, null, {
      params: {
        client_id: config.meta.appId,
        client_secret: config.meta.appSecret,
        grant_type: 'authorization_code',
        redirect_uri: config.meta.redirectUri,
        code,
      },
    });

    const { access_token: shortToken } = tokenResponse.data;

    // Exchange for long-lived token
    const longLivedResponse = await axios.get(META_LONG_LIVED_URL, {
      params: {
        grant_type: 'th_exchange_token',
        client_secret: config.meta.appSecret,
        access_token: shortToken,
      },
    });

    const { access_token: longToken, expires_in } = longLivedResponse.data;

    // Fetch user profile
    const profile = await threadsService.getUserProfile(longToken);

    // Upsert user in DB (requires Sequelize models to be initialized)
    // Dynamically require to avoid circular dep and to allow testing without DB
    let user;
    try {
      const { User } = require('../models');
      [user] = await User.findOrCreate({
        where: { threadsUserId: profile.id },
        defaults: {
          accessToken: longToken,
          tokenExpiresAt: new Date(Date.now() + expires_in * 1000),
          username: profile.username,
          profilePic: profile.threads_profile_picture_url,
        },
      });

      if (user) {
        await user.update({
          accessToken: longToken,
          tokenExpiresAt: new Date(Date.now() + expires_in * 1000),
          username: profile.username,
          profilePic: profile.threads_profile_picture_url,
        });
      }
    } catch (dbErr) {
      console.warn('[Auth] DB upsert failed (DB may not be initialized):', dbErr.message);
      user = { id: profile.id, username: profile.username };
    }

    // Issue JWT
    const jwtToken = jwt.sign(
      { userId: user.id, threadsUserId: profile.id, username: profile.username },
      config.jwtSecret,
      { expiresIn: '7d' }
    );

    const payload = {
      type: 'oauth_success',
      token: jwtToken,
      user: {
        id: user.id,
        username: profile.username,
        profilePic: profile.threads_profile_picture_url,
      },
    };

    return res.status(200).send(buildPostMessageHtml(payload, targetOrigin));
  } catch (err) {
    console.error('[Auth] OAuth callback error:', err.message);
    return res
      .status(500)
      .send(buildPostMessageHtml({ type: 'oauth_error', error: 'OAuth authentication failed' }, targetOrigin));
  }
}

/**
 * Log out the current user.
 * JWT is stateless so the client is responsible for discarding the token;
 * this endpoint acknowledges the logout request.
 */
async function logout(req, res) {
  return res.json({ message: 'Logged out successfully' });
}

/**
 * Refresh a Threads access token.
 */
async function refreshToken(req, res) {
  const { userId } = req.user;
  try {
    const { User } = require('../models');
    const user = await User.findByPk(userId);
    if (!user) return res.status(404).json({ error: 'User not found' });

    const refreshed = await threadsService.refreshToken(user.accessToken);
    await user.update({
      accessToken: refreshed.access_token,
      tokenExpiresAt: new Date(Date.now() + refreshed.expires_in * 1000),
    });

    return res.json({ message: 'Token refreshed successfully' });
  } catch (err) {
    console.error('[Auth] Token refresh error:', err.message);
    return res.status(500).json({ error: 'Token refresh failed', details: err.message });
  }
}

/**
 * Get current user profile.
 */
async function getProfile(req, res) {
  try {
    const { User } = require('../models');
    const user = await User.findByPk(req.user.userId, {
      attributes: ['id', 'threadsUserId', 'username', 'profilePic', 'tokenExpiresAt', 'createdAt'],
    });
    if (!user) return res.status(404).json({ error: 'User not found' });
    return res.json(user);
  } catch (err) {
    console.error('[Auth] Get profile error:', err.message);
    return res.status(500).json({ error: 'Failed to fetch profile' });
  }
}

module.exports = { initiateOAuth, handleCallback, refreshToken, getProfile, logout };
